# Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
EXPOSE 5000
EXPOSE 5001
COPY ["LoveKafe_BE.csproj", "./"]
RUN dotnet restore "LoveKafe_BE.csproj"
COPY . .
RUN dotnet build "LoveKafe_BE.csproj" -c Release -o /app/build

# Publish stage 
FROM build AS publish
RUN dotnet publish "LoveKafe_BE.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "LoveKafe_BE.dll"]