# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY LoveKafe_BE/*.csproj ./LoveKafe_BE/
RUN dotnet restore

# copy everything else and build app
COPY LoveKafe_BE/. ./LoveKafe_BE/
WORKDIR /source/LoveKafe_BE
RUN dotnet publish -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "LoveKafe_BE.dll"]